// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHXSOK0nmMqcPyyxv8JmCAmYIUs0SZhP8',
    appId: '1:486976040470:web:490db3591356be06060f37',
    messagingSenderId: '486976040470',
    projectId: 'prog4swsys',
    authDomain: 'prog4swsys.firebaseapp.com',
    storageBucket: 'prog4swsys.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMr0q3eXoC_GXVusE2jofP-TkKLn9BgFk',
    appId: '1:486976040470:android:0d90d757921d7a97060f37',
    messagingSenderId: '486976040470',
    projectId: 'prog4swsys',
    storageBucket: 'prog4swsys.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJsfVpo_wqjeb2MJdVmSqoQ3YkvCGYwYg',
    appId: '1:486976040470:ios:9edcecd785b96c14060f37',
    messagingSenderId: '486976040470',
    projectId: 'prog4swsys',
    storageBucket: 'prog4swsys.firebasestorage.app',
    androidClientId: '486976040470-4qcmr3tu48g43jjpbfaij07jjb969ff2.apps.googleusercontent.com',
    iosClientId: '486976040470-f9ki1kcu1k352rii1kobjb2hlmkc2c5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj4swsys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHXSOK0nmMqcPyyxv8JmCAmYIUs0SZhP8',
    appId: '1:486976040470:web:21bf6c65e4d736b4060f37',
    messagingSenderId: '486976040470',
    projectId: 'prog4swsys',
    authDomain: 'prog4swsys.firebaseapp.com',
    storageBucket: 'prog4swsys.firebasestorage.app',
  );
}
